"""Authoritative Word Blanks Curriculum and Puzzle Dataset.

Defines the complete 17-level progressive linguistic curriculum containing 450+
curated generative puzzle stems spanning onsets, medial vowels, codas, blends,
digraphs, compound words, distributed templates, and morphological affixes.
"""

from typing import List
from app.schemas.puzzles import DifficultyLevel
from app.schemas.word_blanks import WordBlanksLevel, WordBlanksPuzzle

# ---------------------------------------------------------------------------
# RAW CURRICULUM DEFINITION (17 Progressive Levels)
# ---------------------------------------------------------------------------

RAW_LEVELS = [
    {
        "level": 1,
        "difficulty": DifficultyLevel.BEGINNER,
        "title": "3-Letter Onset Blanks",
        "description": "Recall initial consonant onsets preceding familiar rimes.",
        "xp_per_word": 20,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ A T", "Initial onset before -AT rime."),
            ("_ I N", "Initial onset before -IN rime."),
            ("_ O P", "Initial onset before -OP rime."),
            ("_ U N", "Initial onset before -UN rime."),
            ("_ E T", "Initial onset before -ET rime."),
            ("_ A N", "Initial onset before -AN rime."),
            ("_ I P", "Initial onset before -IP rime."),
            ("_ O T", "Initial onset before -OT rime."),
            ("_ A P", "Initial onset before -AP rime."),
            ("_ E N", "Initial onset before -EN rime."),
            ("_ U G", "Initial onset before -UG rime."),
            ("_ I G", "Initial onset before -IG rime."),
            ("_ O G", "Initial onset before -OG rime."),
            ("_ E D", "Initial onset before -ED rime."),
            ("_ A M", "Initial onset before -AM rime."),
            ("_ A Y", "Initial onset before -AY rime."),
            ("_ O W", "Initial onset before -OW rime."),
            ("_ I T", "Initial onset before -IT rime."),
            ("_ A G", "Initial onset before -AG rime."),
            ("_ A D", "Initial onset before -AD rime."),
            ("_ A B", "Initial onset before -AB rime."),
            ("_ O B", "Initial onset before -OB rime."),
            ("_ U B", "Initial onset before -UB rime."),
            ("_ U T", "Initial onset before -UT rime."),
            ("_ U M", "Initial onset before -UM rime."),
            ("_ O D", "Initial onset before -OD rime."),
            ("_ E G", "Initial onset before -EG rime."),
            ("_ I D", "Initial onset before -ID rime."),
            ("_ U D", "Initial onset before -UD rime."),
            ("_ A X", "Initial onset before -AX rime."),
        ],
    },
    {
        "level": 2,
        "difficulty": DifficultyLevel.BEGINNER,
        "title": "3-Letter Medial Vowels",
        "description": "Substitute and discriminate short vowels (A, E, I, O, U) inside fixed consonant frames.",
        "xp_per_word": 20,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("C _ T", "Medial vowel within C-T frame."),
            ("B _ D", "Medial vowel within B-D frame."),
            ("H _ T", "Medial vowel within H-T frame."),
            ("P _ N", "Medial vowel within P-N frame."),
            ("M _ N", "Medial vowel within M-N frame."),
            ("B _ G", "Medial vowel within B-G frame."),
            ("F _ T", "Medial vowel within F-T frame."),
            ("P _ T", "Medial vowel within P-T frame."),
            ("R _ D", "Medial vowel within R-D frame."),
            ("S _ T", "Medial vowel within S-T frame."),
            ("T _ N", "Medial vowel within T-N frame."),
            ("B _ T", "Medial vowel within B-T frame."),
            ("L _ P", "Medial vowel within L-P frame."),
            ("S _ P", "Medial vowel within S-P frame."),
            ("W _ N", "Medial vowel within W-N frame."),
            ("F _ N", "Medial vowel within F-N frame."),
            ("M _ D", "Medial vowel within M-D frame."),
            ("P _ G", "Medial vowel within P-G frame."),
            ("R _ G", "Medial vowel within R-G frame."),
            ("T _ P", "Medial vowel within T-P frame."),
            ("D _ G", "Medial vowel within D-G frame."),
            ("L _ G", "Medial vowel within L-G frame."),
            ("B _ N", "Medial vowel within B-N frame."),
            ("H _ N", "Medial vowel within H-N frame."),
            ("P _ P", "Medial vowel within P-P frame."),
            ("S _ N", "Medial vowel within S-N frame."),
            ("F _ X", "Medial vowel within F-X frame."),
            ("B _ X", "Medial vowel within B-X frame."),
            ("M _ P", "Medial vowel within M-P frame."),
            ("T _ G", "Medial vowel within T-G frame."),
        ],
    },
    {
        "level": 3,
        "difficulty": DifficultyLevel.BEGINNER,
        "title": "3-Letter Coda Endings",
        "description": "Explore terminal consonant codas and word-ending phonograms.",
        "xp_per_word": 20,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("C A _", "Coda consonant following CA-."),
            ("B A _", "Coda consonant following BA-."),
            ("P I _", "Coda consonant following PI-."),
            ("S E _", "Coda consonant following SE-."),
            ("D A _", "Coda consonant following DA-."),
            ("F A _", "Coda consonant following FA-."),
            ("M A _", "Coda consonant following MA-."),
            ("H A _", "Coda consonant following HA-."),
            ("S U _", "Coda consonant following SU-."),
            ("T O _", "Coda consonant following TO-."),
            ("B E _", "Coda consonant following BE-."),
            ("R A _", "Coda consonant following RA-."),
            ("P A _", "Coda consonant following PA-."),
            ("T I _", "Coda consonant following TI-."),
            ("W I _", "Coda consonant following WI-."),
            ("T A _", "Coda consonant following TA-."),
            ("L A _", "Coda consonant following LA-."),
            ("B O _", "Coda consonant following BO-."),
            ("C O _", "Coda consonant following CO-."),
            ("D O _", "Coda consonant following DO-."),
            ("G O _", "Coda consonant following GO-."),
            ("N O _", "Coda consonant following NO-."),
            ("S O _", "Coda consonant following SO-."),
            ("L O _", "Coda consonant following LO-."),
            ("M O _", "Coda consonant following MO-."),
            ("W A _", "Coda consonant following WA-."),
            ("R E _", "Coda consonant following RE-."),
            ("H E _", "Coda consonant following HE-."),
            ("M E _", "Coda consonant following ME-."),
            ("D E _", "Coda consonant following DE-."),
        ],
    },
    {
        "level": 4,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "title": "4-Letter Silent-E & Rhymes",
        "description": "Master magic-e long vowel rimes and 4-letter rhyming matrices.",
        "xp_per_word": 30,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ A M E", "Onset before -AME rime."),
            ("_ I N E", "Onset before -INE rime."),
            ("_ A K E", "Onset before -AKE rime."),
            ("_ I L L", "Onset before -ILL rime."),
            ("_ E S T", "Onset before -EST rime."),
            ("_ O A T", "Onset before -OAT rime."),
            ("_ A L L", "Onset before -ALL rime."),
            ("_ I C K", "Onset before -ICK rime."),
            ("_ I N G", "Onset before -ING rime."),
            ("_ E L L", "Onset before -ELL rime."),
            ("_ A T E", "Onset before -ATE rime."),
            ("_ A V E", "Onset before -AVE rime."),
            ("_ A C K", "Onset before -ACK rime."),
            ("_ O C K", "Onset before -OCK rime."),
            ("_ U C K", "Onset before -UCK rime."),
            ("_ O O K", "Onset before -OOK rime."),
            ("_ O R N", "Onset before -ORN rime."),
            ("_ A R K", "Onset before -ARK rime."),
            ("_ I N K", "Onset before -INK rime."),
            ("_ U N K", "Onset before -UNK rime."),
            ("_ A N K", "Onset before -ANK rime."),
            ("_ E E D", "Onset before -EED rime."),
            ("_ E E L", "Onset before -EEL rime."),
            ("_ E E T", "Onset before -EET rime."),
            ("_ O O M", "Onset before -OOM rime."),
            ("_ O R E", "Onset before -ORE rime."),
            ("_ I D E", "Onset before -IDE rime."),
            ("_ I T E", "Onset before -ITE rime."),
            ("_ A L E", "Onset before -ALE rime."),
            ("_ O L E", "Onset before -OLE rime."),
        ],
    },
    {
        "level": 5,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "title": "4-Letter Terminal Codas",
        "description": "Distinguish terminal consonant blends and codas (-ST, -FT, -NT, -RT, -ND).",
        "xp_per_word": 30,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("L I _ T", "Terminal blend within LI-T frame."),
            ("B E _ T", "Terminal blend within BE-T frame."),
            ("P A _ T", "Terminal blend within PA-T frame."),
            ("F A _ T", "Terminal blend within FA-T frame."),
            ("W E _ T", "Terminal blend within WE-T frame."),
            ("H E _ P", "Terminal blend within HE-P frame."),
            ("S I _ K", "Terminal blend within SI-K frame."),
            ("M I _ K", "Terminal blend within MI-K frame."),
            ("B A _ K", "Terminal blend within BA-K frame."),
            ("S O _ T", "Terminal blend within SO-T frame."),
            ("R O _ T", "Terminal blend within RO-T frame."),
            ("C O _ T", "Terminal blend within CO-T frame."),
            ("D A _ T", "Terminal blend within DA-T frame."),
            ("C A _ T", "Terminal blend within CA-T frame."),
            ("D U _ T", "Terminal blend within DU-T frame."),
            ("R U _ T", "Terminal blend within RU-T frame."),
            ("W I _ H", "Terminal blend within WI-H frame."),
            ("F I _ H", "Terminal blend within FI-H frame."),
            ("D I _ H", "Terminal blend within DI-H frame."),
            ("W A _ H", "Terminal blend within WA-H frame."),
            ("M U _ T", "Terminal blend within MU-T frame."),
            ("L U _ T", "Terminal blend within LU-T frame."),
            ("B U _ T", "Terminal blend within BU-T frame."),
            ("C A _ P", "Terminal blend within CA-P frame."),
            ("L A _ P", "Terminal blend within LA-P frame."),
        ],
    },
    {
        "level": 6,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "title": "4-Letter Bounded Vowels",
        "description": "Vowel alternation inside 4-letter geminate, nasal, and stop frames.",
        "xp_per_word": 35,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("B _ L L", "Medial vowel within B-LL frame."),
            ("F _ L L", "Medial vowel within F-LL frame."),
            ("W _ L L", "Medial vowel within W-LL frame."),
            ("T _ L L", "Medial vowel within T-LL frame."),
            ("S _ N G", "Medial vowel within S-NG frame."),
            ("R _ N G", "Medial vowel within R-NG frame."),
            ("K _ N G", "Medial vowel within K-NG frame."),
            ("W _ N G", "Medial vowel within W-NG frame."),
            ("B _ N D", "Medial vowel within B-ND frame."),
            ("S _ N D", "Medial vowel within S-ND frame."),
            ("L _ N D", "Medial vowel within L-ND frame."),
            ("F _ N D", "Medial vowel within F-ND frame."),
            ("P _ C K", "Medial vowel within P-CK frame."),
            ("L _ C K", "Medial vowel within L-CK frame."),
            ("D _ C K", "Medial vowel within D-CK frame."),
            ("R _ C K", "Medial vowel within R-CK frame."),
            ("S _ C K", "Medial vowel within S-CK frame."),
            ("T _ C K", "Medial vowel within T-CK frame."),
            ("W _ C K", "Medial vowel within W-CK frame."),
            ("B _ N K", "Medial vowel within B-NK frame."),
            ("S _ N K", "Medial vowel within S-NK frame."),
            ("T _ N K", "Medial vowel within T-NK frame."),
            ("R _ N K", "Medial vowel within R-NK frame."),
            ("L _ N K", "Medial vowel within L-NK frame."),
            ("P _ N K", "Medial vowel within P-NK frame."),
        ],
    },
    {
        "level": 7,
        "difficulty": DifficultyLevel.INTERMEDIATE,
        "title": "4-Letter Vowel Digraphs",
        "description": "Internal vowel teams and digraphs (EA, EE, OA, OO, OU, AI).",
        "xp_per_word": 35,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("B _ _ T", "Vowel digraph inside B-T frame."),
            ("M _ _ T", "Vowel digraph inside M-T frame."),
            ("S _ _ P", "Vowel digraph inside S-P frame."),
            ("W _ _ D", "Vowel digraph inside W-D frame."),
            ("C _ _ T", "Vowel digraph inside C-T frame."),
            ("F _ _ T", "Vowel digraph inside F-T frame."),
            ("R _ _ D", "Vowel digraph inside R-D frame."),
            ("H _ _ D", "Vowel digraph inside H-D frame."),
            ("L _ _ D", "Vowel digraph inside L-D frame."),
            ("S _ _ D", "Vowel digraph inside S-D frame."),
            ("T _ _ M", "Vowel digraph inside T-M frame."),
            ("D _ _ P", "Vowel digraph inside D-P frame."),
            ("R _ _ F", "Vowel digraph inside R-F frame."),
            ("S _ _ L", "Vowel digraph inside S-L frame."),
            ("T _ _ L", "Vowel digraph inside T-L frame."),
            ("P _ _ L", "Vowel digraph inside P-L frame."),
            ("B _ _ N", "Vowel digraph inside B-N frame."),
            ("M _ _ N", "Vowel digraph inside M-N frame."),
            ("S _ _ N", "Vowel digraph inside S-N frame."),
            ("L _ _ N", "Vowel digraph inside L-N frame."),
            ("R _ _ N", "Vowel digraph inside R-N frame."),
            ("P _ _ N", "Vowel digraph inside P-N frame."),
            ("C _ _ N", "Vowel digraph inside C-N frame."),
            ("G _ _ L", "Vowel digraph inside G-L frame."),
            ("F _ _ L", "Vowel digraph inside F-L frame."),
            ("W _ _ L", "Vowel digraph inside W-L frame."),
            ("P _ _ T", "Vowel digraph inside P-T frame."),
            ("R _ _ T", "Vowel digraph inside R-T frame."),
            ("B _ _ K", "Vowel digraph inside B-K frame."),
            ("C _ _ K", "Vowel digraph inside C-K frame."),
        ],
    },
    {
        "level": 8,
        "difficulty": DifficultyLevel.ADVANCED,
        "title": "4-Letter Initial Blends",
        "description": "Beginning consonant digraphs and blends (CH, SH, TH, FL, DR, ST, GR).",
        "xp_per_word": 45,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ _ A T", "Initial blend before -AT."),
            ("_ _ I P", "Initial blend before -IP."),
            ("_ _ O P", "Initial blend before -OP."),
            ("_ _ U M", "Initial blend before -UM."),
            ("_ _ A P", "Initial blend before -AP."),
            ("_ _ I N", "Initial blend before -IN."),
            ("_ _ E D", "Initial blend before -ED."),
            ("_ _ A M", "Initial blend before -AM."),
            ("_ _ I T", "Initial blend before -IT."),
            ("_ _ O T", "Initial blend before -OT."),
            ("_ _ A N", "Initial blend before -AN."),
            ("_ _ E N", "Initial blend before -EN."),
            ("_ _ I G", "Initial blend before -IG."),
            ("_ _ O G", "Initial blend before -OG."),
            ("_ _ U G", "Initial blend before -UG."),
            ("_ _ A R", "Initial blend before -AR."),
            ("_ _ O R", "Initial blend before -OR."),
            ("_ _ A Y", "Initial blend before -AY."),
            ("_ _ O W", "Initial blend before -OW."),
            ("_ _ E E", "Initial blend before -EE."),
            ("_ _ E W", "Initial blend before -EW."),
            ("_ _ A W", "Initial blend before -AW."),
            ("_ _ A B", "Initial blend before -AB."),
            ("_ _ A D", "Initial blend before -AD."),
            ("_ _ A G", "Initial blend before -AG."),
        ],
    },
    {
        "level": 9,
        "difficulty": DifficultyLevel.ADVANCED,
        "title": "5-Letter Medial Sandwiches",
        "description": "5-letter vocabulary words requiring single vowel/consonant recall.",
        "xp_per_word": 55,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("S T _ N D", "Medial vowel in ST-ND frame."),
            ("T R _ I N", "Medial vowel in TR-IN frame."),
            ("B L _ N K", "Medial vowel in BL-NK frame."),
            ("C R _ W D", "Medial vowel in CR-WD frame."),
            ("P L _ N T", "Medial vowel in PL-NT frame."),
            ("C H _ I R", "Medial vowel in CH-IR frame."),
            ("F L _ A T", "Medial vowel in FL-AT frame."),
            ("S P _ O N", "Medial vowel in SP-ON frame."),
            ("B R _ I N", "Medial vowel in BR-IN frame."),
            ("G R _ A T", "Medial vowel in GR-AT frame."),
            ("S C _ N E", "Medial vowel in SC-NE frame."),
            ("S H _ R K", "Medial vowel in SH-RK frame."),
            ("S M _ L E", "Medial vowel in SM-LE frame."),
            ("S N _ K E", "Medial vowel in SN-KE frame."),
            ("S P _ C E", "Medial vowel in SP-CE frame."),
            ("S T _ O L", "Medial vowel in ST-OL frame."),
            ("S W _ E T", "Medial vowel in SW-ET frame."),
            ("T R _ C K", "Medial vowel in TR-CK frame."),
            ("C H _ C K", "Medial vowel in CH-CK frame."),
            ("C R _ N E", "Medial vowel in CR-NE frame."),
            ("F L _ S H", "Medial vowel in FL-SH frame."),
            ("G L _ S S", "Medial vowel in GL-SS frame."),
            ("P L _ T E", "Medial vowel in PL-TE frame."),
            ("S H _ R T", "Medial vowel in SH-RT frame."),
            ("C L _ O K", "Medial vowel in CL-OK frame."),
        ],
    },
    {
        "level": 10,
        "difficulty": DifficultyLevel.ADVANCED,
        "title": "5-Letter Vowel Diphthongs",
        "description": "5-letter words with dual blanks resolving vowel teams and diphthongs.",
        "xp_per_word": 60,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("S P _ _ K", "Dual blank within SP-K frame."),
            ("S T _ _ M", "Dual blank within ST-M frame."),
            ("C L _ _ D", "Dual blank within CL-D frame."),
            ("G R _ _ N", "Dual blank within GR-N frame."),
            ("B R _ _ D", "Dual blank within BR-D frame."),
            ("T R _ _ K", "Dual blank within TR-K frame."),
            ("C R _ _ N", "Dual blank within CR-N frame."),
            ("F L _ _ T", "Dual blank within FL-T frame."),
            ("S L _ _ P", "Dual blank within SL-P frame."),
            ("S T _ _ N", "Dual blank within ST-N frame."),
            ("S H _ _ P", "Dual blank within SH-P frame."),
            ("P L _ _ T", "Dual blank within PL-T frame."),
            ("B L _ _ D", "Dual blank within BL-D frame."),
            ("D R _ _ N", "Dual blank within DR-N frame."),
            ("F R _ _ T", "Dual blank within FR-T frame."),
            ("S W _ _ T", "Dual blank within SW-T frame."),
            ("S C _ _ P", "Dual blank within SC-P frame."),
            ("S M _ _ K", "Dual blank within SM-K frame."),
            ("S N _ _ K", "Dual blank within SN-K frame."),
            ("S H _ _ T", "Dual blank within SH-T frame."),
            ("C H _ _ T", "Dual blank within CH-T frame."),
            ("B R _ _ K", "Dual blank within BR-K frame."),
            ("C L _ _ N", "Dual blank within CL-N frame."),
            ("F L _ _ K", "Dual blank within FL-K frame."),
            ("T R _ _ T", "Dual blank within TR-T frame."),
        ],
    },
    {
        "level": 11,
        "difficulty": DifficultyLevel.ADVANCED,
        "title": "5-Letter Initial Blends",
        "description": "5-letter word families with double blank onsets (__LLL).",
        "xp_per_word": 65,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ _ A N D", "Double onset before -AND."),
            ("_ _ I N T", "Double onset before -INT."),
            ("_ _ A R T", "Double onset before -ART."),
            ("_ _ E S T", "Double onset before -EST."),
            ("_ _ A N K", "Double onset before -ANK."),
            ("_ _ I N G", "Double onset before -ING."),
            ("_ _ I C K", "Double onset before -ICK."),
            ("_ _ O C K", "Double onset before -OCK."),
            ("_ _ U C K", "Double onset before -UCK."),
            ("_ _ A C K", "Double onset before -ACK."),
            ("_ _ I L L", "Double onset before -ILL."),
            ("_ _ E L L", "Double onset before -ELL."),
            ("_ _ A L L", "Double onset before -ALL."),
            ("_ _ I S H", "Double onset before -ISH."),
            ("_ _ U S H", "Double onset before -USH."),
            ("_ _ A S H", "Double onset before -ASH."),
            ("_ _ E S S", "Double onset before -ESS."),
            ("_ _ I S S", "Double onset before -ISS."),
            ("_ _ O S S", "Double onset before -OSS."),
            ("_ _ U N T", "Double onset before -UNT."),
            ("_ _ I N K", "Double onset before -INK."),
            ("_ _ A R M", "Double onset before -ARM."),
            ("_ _ O R M", "Double onset before -ORM."),
            ("_ _ O R N", "Double onset before -ORN."),
            ("_ _ A R K", "Double onset before -ARK."),
        ],
    },
    {
        "level": 12,
        "difficulty": DifficultyLevel.MASTER,
        "title": "6-Letter Compound Words",
        "description": "Construct 6-letter compound words from recognizable 3-letter syllable roots.",
        "xp_per_word": 80,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("S U N _ _ _", "Compound word beginning with SUN-."),
            ("B E D _ _ _", "Compound word beginning with BED-."),
            ("S E A _ _ _", "Compound word beginning with SEA-."),
            ("_ _ _ B O X", "Compound word ending with -BOX."),
            ("_ _ _ D O G", "Compound word ending with -DOG."),
            ("_ _ _ M A N", "Compound word ending with -MAN."),
            ("_ _ _ D A Y", "Compound word ending with -DAY."),
            ("_ _ _ T O P", "Compound word ending with -TOP."),
            ("_ _ _ B A G", "Compound word ending with -BAG."),
            ("C U P _ _ _", "Compound word beginning with CUP-."),
            ("P E N _ _ _", "Compound word beginning with PEN-."),
            ("P O T _ _ _", "Compound word beginning with POT-."),
            ("C A T _ _ _", "Compound word beginning with CAT-."),
            ("B O X _ _ _", "Compound word beginning with BOX-."),
            ("F O O T _ _", "Compound word beginning with FOOT-."),
            ("B A C K _ _", "Compound word beginning with BACK-."),
            ("P L A Y _ _", "Compound word beginning with PLAY-."),
            ("F I R E _ _", "Compound word beginning with FIRE-."),
            ("W O O D _ _", "Compound word beginning with WOOD-."),
            ("R A I N _ _", "Compound word beginning with RAIN-."),
            ("S N O W _ _", "Compound word beginning with SNOW-."),
            ("G O L D _ _", "Compound word beginning with GOLD-."),
            ("W I N D _ _", "Compound word beginning with WIND-."),
            ("B O O K _ _", "Compound word beginning with BOOK-."),
            ("L I F E _ _", "Compound word beginning with LIFE-."),
        ],
    },
    {
        "level": 13,
        "difficulty": DifficultyLevel.MASTER,
        "title": "6-Letter Distributed Templates",
        "description": "Master 6-letter morphology across distributed onset, nucleus, and coda blanks.",
        "xp_per_word": 90,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ R _ N _ H", "Distributed onset, nucleus, coda blanks."),
            ("S _ R _ N _", "Distributed blanks inside S-R-N frame."),
            ("_ L _ G _ T", "Distributed blanks before -GHT."),
            ("B _ _ G _ T", "Distributed blanks in B-GHT frame."),
            ("_ P _ I _ E", "Distributed blanks."),
            ("C _ _ N _ H", "Distributed blanks in C-NCH frame."),
            ("S _ _ I _ H", "Distributed blanks in S-SH frame."),
            ("T _ _ N _ H", "Distributed blanks in T-NCH frame."),
            ("G _ _ U _ D", "Distributed blanks in G-UND frame."),
            ("_ L _ M _ E", "Distributed blanks."),
            ("_ R _ C _ E", "Distributed blanks."),
            ("_ P _ E _ D", "Distributed blanks."),
            ("_ T _ I _ E", "Distributed blanks."),
            ("_ R _ A _ H", "Distributed blanks."),
            ("_ P _ A _ H", "Distributed blanks."),
            ("_ L _ A _ H", "Distributed blanks."),
            ("_ T _ A _ N", "Distributed blanks."),
            ("_ P _ I _ G", "Distributed blanks."),
            ("_ T _ I _ G", "Distributed blanks."),
            ("_ L _ I _ H", "Distributed blanks."),
            ("_ R _ I _ H", "Distributed blanks."),
            ("_ P _ A _ K", "Distributed blanks."),
            ("_ T _ A _ P", "Distributed blanks."),
            ("_ L _ A _ K", "Distributed blanks."),
            ("_ R _ A _ P", "Distributed blanks."),
        ],
    },
    {
        "level": 14,
        "difficulty": DifficultyLevel.MASTER,
        "title": "6-Letter Inflectional Suffixes",
        "description": "Agent nouns (-ER), continuous verbs (-ING), and past tense (-ED).",
        "xp_per_word": 95,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ _ _ K E R", "Agent suffix -KER."),
            ("_ _ _ I N G", "Continuous suffix -ING."),
            ("_ _ _ D E R", "Comparative/agent suffix -DER."),
            ("_ _ _ T E R", "Agent suffix -TER."),
            ("_ _ _ L E S", "Plural noun suffix -LES."),
            ("_ _ _ P E R", "Agent suffix -PER."),
            ("_ _ _ V E R", "Agent suffix -VER."),
            ("_ _ _ G E R", "Agent suffix -GER."),
            ("_ _ _ M E R", "Agent suffix -MER."),
            ("_ _ _ N E R", "Agent suffix -NER."),
            ("_ _ _ B E R", "Agent suffix -BER."),
            ("_ _ _ S E R", "Agent suffix -SER."),
            ("_ _ _ L E R", "Agent suffix -LER."),
            ("_ _ _ R E D", "Past tense suffix -RED."),
            ("_ _ _ T E D", "Past tense suffix -TED."),
            ("_ _ _ L E D", "Past tense suffix -LED."),
            ("_ _ _ N E D", "Past tense suffix -NED."),
            ("_ _ _ S E D", "Past tense suffix -SED."),
            ("_ _ _ D E D", "Past tense suffix -DED."),
            ("_ _ _ M E D", "Past tense suffix -MED."),
            ("_ _ _ P E D", "Past tense suffix -PED."),
            ("_ _ _ K E D", "Past tense suffix -KED."),
            ("_ _ _ F E D", "Past tense suffix -FED."),
            ("_ _ _ B E D", "Past tense suffix -BED."),
            ("_ _ _ G E D", "Past tense suffix -GED."),
        ],
    },
    {
        "level": 15,
        "difficulty": DifficultyLevel.MASTER,
        "title": "Common Base Prefixes (UN-, RE-, DIS-)",
        "description": "Negation, reversal, and iteration prefixes on base root words.",
        "xp_per_word": 110,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("U N _ _ _ _", "Reversal/negation prefix UN-."),
            ("R E _ _ _ _", "Iteration prefix RE-."),
            ("D I S _ _ _", "Separation/negation prefix DIS-."),
            ("I N _ _ _ _", "Inward/negation prefix IN-."),
            ("I M _ _ _ _", "Inward prefix IM-."),
            ("M I S _ _ _", "Erroneous prefix MIS-."),
            ("P R E _ _ _", "Temporal prefix PRE-."),
            ("N O N _ _ _", "Negation prefix NON-."),
            ("S U B _ _ _", "Underneath prefix SUB-."),
            ("O U T _ _ _", "Surpassing prefix OUT-."),
            ("U N _ _ _", "Short UN- prefix words."),
            ("R E _ _ _", "Short RE- prefix words."),
            ("D I S _ _", "Short DIS- prefix words."),
            ("M I S _ _", "Short MIS- words."),
            ("P R E _ _", "Short PRE- words."),
            ("S U B _ _", "Short SUB- words."),
            ("O U T _ _", "Short OUT- words."),
            ("O V E R _", "Short OVER- words."),
            ("U N _ _ _ _ _", "7-letter UN- words."),
            ("R E _ _ _ _ _", "7-letter RE- words."),
            ("D I S _ _ _ _", "7-letter DIS- words."),
            ("M I S _ _ _ _", "7-letter MIS- words."),
            ("P R E _ _ _ _", "7-letter PRE- words."),
            ("O U T _ _ _ _", "7-letter OUT- words."),
            ("S U B _ _ _ _", "7-letter SUB- words."),
        ],
    },
    {
        "level": 16,
        "difficulty": DifficultyLevel.MASTER,
        "title": "Derivational Suffixes (-FUL, -LESS, -NESS)",
        "description": "Morphemic suffixes transforming word classes (nouns, adjectives, adverbs).",
        "xp_per_word": 125,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("_ _ _ F U L", "Adjective suffix -FUL."),
            ("_ _ _ L E S S", "Adjective suffix -LESS."),
            ("_ _ _ N E S S", "Noun suffix -NESS."),
            ("_ _ _ M E N T", "Noun suffix -MENT."),
            ("_ _ _ A B L E", "Adjective suffix -ABLE."),
            ("_ _ _ I B L E", "Adjective suffix -IBLE."),
            ("_ _ _ T I O N", "Noun suffix -TION."),
            ("_ _ _ S I O N", "Noun suffix -SION."),
            ("_ _ _ H O O D", "Noun suffix -HOOD."),
            ("_ _ _ S H I P", "Noun suffix -SHIP."),
            ("_ _ _ W A R D", "Directional suffix -WARD."),
            ("_ _ _ L I K E", "Adjective suffix -LIKE."),
            ("_ _ _ F U L L", "Full words."),
            ("_ _ _ O U S", "Adjective suffix -OUS."),
            ("_ _ _ I S H", "Adjective suffix -ISH."),
            ("_ _ _ A N T", "Noun/adjective suffix -ANT."),
            ("_ _ _ E N T", "Noun/adjective suffix -ENT."),
            ("_ _ _ A N C E", "Noun suffix -ANCE."),
            ("_ _ _ E N C E", "Noun suffix -ENCE."),
            ("_ _ _ I S T", "Agent suffix -IST."),
            ("_ _ _ I S M", "Noun suffix -ISM."),
            ("_ _ _ I T Y", "Noun suffix -ITY."),
            ("_ _ _ T Y", "Noun suffix -TY."),
            ("_ _ _ R Y", "Noun suffix -RY."),
            ("_ _ _ A R Y", "Noun suffix -ARY."),
        ],
    },
    {
        "level": 17,
        "difficulty": DifficultyLevel.MASTER,
        "title": "Advanced Morphemic Matrices",
        "description": "Polysyllabic Latin/Greek roots and academic morphological matrices.",
        "xp_per_word": 140,
        "min_puzzles_to_unlock_next": 5,
        "stems": [
            ("P R E _ _ _ _", "Prefix PRE-."),
            ("O V E R _ _ _", "Prefix OVER-."),
            ("U N D E R _ _", "Prefix UNDER-."),
            ("S U B _ _ _ _", "Prefix SUB-."),
            ("I N T E R _ _", "Prefix INTER-."),
            ("T R A N S _ _", "Prefix TRANS-."),
            ("S U P E R _ _", "Prefix SUPER-."),
            ("A N T I _ _ _", "Prefix ANTI-."),
            ("A U T O _ _ _", "Prefix AUTO-."),
            ("M U L T I _ _", "Prefix MULTI-."),
            ("M I C R O _ _", "Root MICRO-."),
            ("M A C R O _ _", "Root MACRO-."),
            ("E X T R A _ _", "Prefix EXTRA-."),
            ("P O L Y _ _ _", "Root POLY-."),
            ("M O N O _ _ _", "Root MONO-."),
            ("B I _ _ _ _ _", "Root BI-."),
            ("T R I _ _ _ _", "Root TRI-."),
            ("C E N T _ _ _", "Root CENT-."),
            ("M I L L _ _ _", "Root MILL-."),
            ("H Y P E R _ _", "Root HYPER-."),
            ("C O N _ _ _ _", "Prefix CON-."),
            ("C O M _ _ _ _", "Prefix COM-."),
            ("P E R _ _ _ _", "Prefix PER-."),
            ("P O S T _ _ _", "Prefix POST-."),
            ("T E L E _ _ _", "Prefix TELE-."),
        ],
    },
]


def _build_curriculum() -> List[WordBlanksLevel]:
    """Compiles the raw curriculum specifications into strict WordBlanksLevel domain models."""
    curriculum: List[WordBlanksLevel] = []
    for raw in RAW_LEVELS:
        lvl_num = raw["level"]
        puzzles: List[WordBlanksPuzzle] = []
        for p_idx, (stem, note) in enumerate(raw["stems"], start=1):
            clean_stem = stem.replace(" ", "")
            w_len = len(clean_stem)
            b_cnt = clean_stem.count("_")
            p_id = f"wb-l{lvl_num}-p{p_idx}"
            puzzles.append(
                WordBlanksPuzzle(
                    id=p_id,
                    puzzle_number=p_idx,
                    stem=stem,
                    word_length=w_len,
                    blank_count=b_cnt,
                    min_words_to_clear=3,
                    pedagogical_note=note,
                )
            )

        first_p = puzzles[0]
        curriculum.append(
            WordBlanksLevel(
                level=lvl_num,
                difficulty=raw["difficulty"],
                title=raw["title"],
                description=raw["description"],
                xp_per_word=raw["xp_per_word"],
                min_puzzles_to_unlock_next=len(puzzles),
                puzzles=puzzles,
                stem=first_p.stem,
                word_length=first_p.word_length,
                blank_count=first_p.blank_count,
                min_words_to_unlock=3,
            )
        )
    return curriculum


WORD_BLANKS_CURRICULUM: List[WordBlanksLevel] = _build_curriculum()
